export const pyq = [
  // BCA
  {
    name: "Problem Solving Techniques",
    year: "2026",
    semester: "1st",
    university: "MAKAUT",
    sub_code: "PST101",
    stream: "B.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Algorithms"],
    pdf: "/pyq/pst-2026.pdf",
    uploadedAt: "2026-03-10",
  },
  {
    name: "C Programming",
    year: "2025",
    semester: "1st",
    university: "MAKAUT",
    sub_code: "C101",
    stream: "B.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Loops"],
    pdf: "/pyq/c-2025.pdf",
    uploadedAt: "2025-03-10",
  },
  {
    name: "DBMS",
    year: "2024",
    semester: "3rd",
    university: "MAKAUT",
    sub_code: "DB301",
    stream: "B.C.A",
    type: "Mid Term",
    marks: 30,
    duration: "1.5 Hours",
    topics: ["SQL"],
    pdf: "/pyq/dbms.pdf",
    uploadedAt: "2024-03-10",
  },
  {
    name: "Web Tech",
    year: "2026",
    semester: "3rd",
    university: "MAKAUT",
    sub_code: "WT301",
    stream: "B.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["HTML"],
    pdf: "/pyq/wt.pdf",
    uploadedAt: "2026-03-10",
  },
  {
    name: "Java",
    year: "2025",
    semester: "2nd",
    university: "MAKAUT",
    sub_code: "J201",
    stream: "B.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["OOP"],
    pdf: "/pyq/java.pdf",
    uploadedAt: "2025-03-10",
  },
  {
    name: "Python",
    year: "2024",
    semester: "1st",
    university: "MAKAUT",
    sub_code: "PY101",
    stream: "B.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Basics"],
    pdf: "/pyq/py.pdf",
    uploadedAt: "2024-03-10",
  },

  // MCA
  {
    name: "Advanced Java",
    year: "2026",
    semester: "1st",
    university: "MAKAUT",
    sub_code: "AJ101",
    stream: "M.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Spring"],
    pdf: "/pyq/aj.pdf",
    uploadedAt: "2026-03-10",
  },
  {
    name: "AI",
    year: "2025",
    semester: "2nd",
    university: "MAKAUT",
    sub_code: "AI201",
    stream: "M.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["ML"],
    pdf: "/pyq/ai.pdf",
    uploadedAt: "2025-03-10",
  },
  {
    name: "Cloud",
    year: "2024",
    semester: "3rd",
    university: "MAKAUT",
    sub_code: "CL301",
    stream: "M.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["AWS"],
    pdf: "/pyq/cloud.pdf",
    uploadedAt: "2024-03-10",
  },
  {
    name: "Big Data",
    year: "2026",
    semester: "4th",
    university: "MAKAUT",
    sub_code: "BD401",
    stream: "M.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Hadoop"],
    pdf: "/pyq/bd.pdf",
    uploadedAt: "2026-03-10",
  },
  {
    name: "Cyber Security",
    year: "2025",
    semester: "2nd",
    university: "MAKAUT",
    sub_code: "CS201",
    stream: "M.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Security"],
    pdf: "/pyq/cs.pdf",
    uploadedAt: "2025-03-10",
  },
  {
    name: "DSA",
    year: "2024",
    semester: "1st",
    university: "MAKAUT",
    sub_code: "DS101",
    stream: "M.C.A",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Stack"],
    pdf: "/pyq/dsa.pdf",
    uploadedAt: "2024-03-10",
  },

  // B.TECH
  {
    name: "Operating System",
    year: "2026",
    semester: "4th",
    university: "MAKAUT",
    sub_code: "OS401",
    stream: "B.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Scheduling"],
    pdf: "/pyq/os.pdf",
    uploadedAt: "2026-03-10",
  },
  {
    name: "Networks",
    year: "2025",
    semester: "5th",
    university: "MAKAUT",
    sub_code: "CN501",
    stream: "B.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["TCP"],
    pdf: "/pyq/cn.pdf",
    uploadedAt: "2025-03-10",
  },
  {
    name: "Compiler",
    year: "2024",
    semester: "6th",
    university: "MAKAUT",
    sub_code: "CD601",
    stream: "B.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Parsing"],
    pdf: "/pyq/cd.pdf",
    uploadedAt: "2024-03-10",
  },
  {
    name: "DBMS",
    year: "2026",
    semester: "3rd",
    university: "MAKAUT",
    sub_code: "DB301",
    stream: "B.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["SQL"],
    pdf: "/pyq/db.pdf",
    uploadedAt: "2026-03-10",
  },
  {
    name: "ML",
    year: "2025",
    semester: "7th",
    university: "MAKAUT",
    sub_code: "ML701",
    stream: "B.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Regression"],
    pdf: "/pyq/ml.pdf",
    uploadedAt: "2025-03-10",
  },
  {
    name: "Discrete Math",
    year: "2024",
    semester: "2nd",
    university: "MAKAUT",
    sub_code: "DM201",
    stream: "B.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Logic"],
    pdf: "/pyq/dm.pdf",
    uploadedAt: "2024-03-10",
  },

  // M.TECH
  {
    name: "Deep Learning",
    year: "2026",
    semester: "1st",
    university: "MAKAUT",
    sub_code: "DL101",
    stream: "M.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["NN"],
    pdf: "/pyq/dl.pdf",
    uploadedAt: "2026-03-10",
  },
  {
    name: "IoT",
    year: "2025",
    semester: "2nd",
    university: "MAKAUT",
    sub_code: "IOT201",
    stream: "M.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Sensors"],
    pdf: "/pyq/iot.pdf",
    uploadedAt: "2025-03-10",
  },
  {
    name: "AI Advanced",
    year: "2024",
    semester: "3rd",
    university: "MAKAUT",
    sub_code: "AI301",
    stream: "M.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["ML"],
    pdf: "/pyq/aia.pdf",
    uploadedAt: "2024-03-10",
  },
  {
    name: "Cloud Advanced",
    year: "2026",
    semester: "2nd",
    university: "MAKAUT",
    sub_code: "CL201",
    stream: "M.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["AWS"],
    pdf: "/pyq/cla.pdf",
    uploadedAt: "2026-03-10",
  },
  {
    name: "Cyber Advanced",
    year: "2025",
    semester: "1st",
    university: "MAKAUT",
    sub_code: "CS101",
    stream: "M.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Security"],
    pdf: "/pyq/csa.pdf",
    uploadedAt: "2025-03-10",
  },
  {
    name: "Big Data",
    year: "2024",
    semester: "2nd",
    university: "MAKAUT",
    sub_code: "BD201",
    stream: "M.TECH",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Hadoop"],
    pdf: "/pyq/bd.pdf",
    uploadedAt: "2024-03-10",
  },

  // B.PHARM
  {
    name: "Pharmacology",
    year: "2026",
    semester: "2nd",
    university: "MAKAUT",
    sub_code: "PH201",
    stream: "B.PHARM",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Drugs"],
    pdf: "/pyq/ph.pdf",
    uploadedAt: "2026-03-10",
  },
  {
    name: "Medicinal Chemistry",
    year: "2025",
    semester: "3rd",
    university: "MAKAUT",
    sub_code: "MC301",
    stream: "B.PHARM",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Compounds"],
    pdf: "/pyq/mc.pdf",
    uploadedAt: "2025-03-10",
  },
  {
    name: "Pharmaceutics",
    year: "2024",
    semester: "1st",
    university: "MAKAUT",
    sub_code: "PC101",
    stream: "B.PHARM",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Formulation"],
    pdf: "/pyq/pc.pdf",
    uploadedAt: "2024-03-10",
  },
  {
    name: "Biochemistry",
    year: "2026",
    semester: "2nd",
    university: "MAKAUT",
    sub_code: "BC201",
    stream: "B.PHARM",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Protein"],
    pdf: "/pyq/bc.pdf",
    uploadedAt: "2026-03-10",
  },
  {
    name: "Microbiology",
    year: "2025",
    semester: "4th",
    university: "MAKAUT",
    sub_code: "MB401",
    stream: "B.PHARM",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Bacteria"],
    pdf: "/pyq/mb.pdf",
    uploadedAt: "2025-03-10",
  },
  {
    name: "Pharma Analysis",
    year: "2024",
    semester: "5th",
    university: "MAKAUT",
    sub_code: "PA501",
    stream: "B.PHARM",
    type: "End Semester",
    marks: 70,
    duration: "3 Hours",
    topics: ["Analysis"],
    pdf: "/pyq/pa.pdf",
    uploadedAt: "2024-03-10",
  },
];

export const years = [...new Set(pyq.map(i => i.year))].sort((a, b) => b - a);
export const streams = [...new Set(pyq.map(i => i.stream))];