export const notes = [
    // BCA
    {
        title: "C Programming Complete Notes",
        author: "Rahul Sharma",
        rating: 4.8,
        about: "Comprehensive notes covering C basics, loops, functions, arrays, pointers, and file handling for beginners.",
        price: 99,
        thumbnail: "/notes/c-programming.jpg",
        profileKey: "rahul_sharma",
        stream: "B.C.A",
        pdfPath: "/notes-pdf/c-programming.pdf",
        uploadedAt: "2026-03-10",
    },
    {
        title: "DBMS Handwritten Notes",
        author: "Priya Das",
        rating: 4.7,
        about: "Well-structured DBMS notes including ER model, normalization, SQL, transactions, and indexing.",
        price: 149,
        thumbnail: "/notes/dbms.jpg",
        profileKey: "priya_das",
        stream: "B.C.A",
        pdfPath: "/notes-pdf/dbms.pdf",
        uploadedAt: "2026-03-12",
    },
    {
        title: "Java OOP Notes",
        author: "Ankit Roy",
        rating: 4.6,
        about: "Focused notes on Java programming with strong OOP concepts, inheritance, polymorphism, and exception handling.",
        price: 129,
        thumbnail: "/notes/java.jpg",
        profileKey: "ankit_roy",
        stream: "B.C.A",
        pdfPath: "/notes-pdf/java.pdf",
        uploadedAt: "2026-03-15",
    },

    // MCA
    {
        title: "Advanced Java Notes",
        author: "Sneha Gupta",
        rating: 4.9,
        about: "Detailed notes on JDBC, Servlets, JSP, Spring basics, and enterprise Java development.",
        price: 199,
        thumbnail: "/notes/advanced-java.jpg",
        profileKey: "sneha_gupta",
        stream: "M.C.A",
        pdfPath: "/notes-pdf/advanced-java.pdf",
        uploadedAt: "2026-03-18",
    },
    {
        title: "Artificial Intelligence Notes",
        author: "Vikash Singh",
        rating: 4.8,
        about: "Concept-based AI notes covering search algorithms, machine learning basics, expert systems, and NLP.",
        price: 179,
        thumbnail: "/notes/ai.jpg",
        profileKey: "vikash_singh",
        stream: "M.C.A",
        pdfPath: "/notes-pdf/ai.pdf",
        uploadedAt: "2026-03-20",
    },
    {
        title: "Cloud Computing Notes",
        author: "Neha Paul",
        rating: 4.7,
        about: "Complete notes for cloud concepts, virtualization, AWS basics, SaaS, PaaS, and deployment models.",
        price: 189,
        thumbnail: "/notes/cloud.jpg",
        profileKey: "neha_paul",
        stream: "M.C.A",
        pdfPath: "/notes-pdf/cloud.pdf",
        uploadedAt: "2026-03-22",
    },

    // B.TECH
    {
        title: "Operating System Notes",
        author: "Sourav Ghosh",
        rating: 4.8,
        about: "Detailed notes on process management, CPU scheduling, deadlocks, memory management, and file systems.",
        price: 159,
        thumbnail: "/notes/os.jpg",
        profileKey: "sourav_ghosh",
        stream: "B.TECH",
        pdfPath: "/notes-pdf/os.pdf",
        uploadedAt: "2026-03-25",
    },
    {
        title: "Computer Networks Notes",
        author: "Ritika Jain",
        rating: 4.7,
        about: "Covers OSI model, TCP/IP, routing, switching, protocols, and network security basics.",
        price: 169,
        thumbnail: "/notes/networks.jpg",
        profileKey: "ritika_jain",
        stream: "B.TECH",
        pdfPath: "/notes-pdf/networks.pdf",
        uploadedAt: "2026-03-27",
    },
    {
        title: "Machine Learning Notes",
        author: "Aditya Verma",
        rating: 4.9,
        about: "High-quality notes on regression, classification, supervised learning, unsupervised learning, and evaluation metrics.",
        price: 219,
        thumbnail: "/notes/ml.jpg",
        profileKey: "aditya_verma",
        stream: "B.TECH",
        pdfPath: "/notes-pdf/ml.pdf",
        uploadedAt: "2026-03-29",
    },

    // M.TECH
    {
        title: "Deep Learning Notes",
        author: "Kunal Mehta",
        rating: 4.9,
        about: "Advanced notes covering neural networks, CNN, RNN, backpropagation, and practical DL concepts.",
        price: 249,
        thumbnail: "/notes/deep-learning.jpg",
        profileKey: "kunal_mehta",
        stream: "M.TECH",
        pdfPath: "/notes-pdf/deep-learning.pdf",
        uploadedAt: "2026-04-01",
    },
    {
        title: "IoT Complete Notes",
        author: "Pooja Sen",
        rating: 4.6,
        about: "Complete IoT notes with sensors, protocols, cloud integration, architecture, and applications.",
        price: 189,
        thumbnail: "/notes/iot.jpg",
        profileKey: "pooja_sen",
        stream: "M.TECH",
        pdfPath: "/notes-pdf/iot.pdf",
        uploadedAt: "2026-04-03",
    },

    // B.PHARM
    {
        title: "Pharmacology Notes",
        author: "Ananya Bose",
        rating: 4.8,
        about: "Easy-to-understand pharmacology notes including drug classification, mechanisms, and therapeutic uses.",
        price: 199,
        thumbnail: "/notes/pharmacology.jpg",
        profileKey: "ananya_bose",
        stream: "B.PHARM",
        pdfPath: "/notes-pdf/pharmacology.pdf",
        uploadedAt: "2026-04-05",
    },
    {
        title: "Medicinal Chemistry Notes",
        author: "Rohit Pal",
        rating: 4.7,
        about: "Detailed medicinal chemistry notes covering compounds, synthesis, SAR, and pharmaceutical importance.",
        price: 209,
        thumbnail: "/notes/medicinal-chemistry.jpg",
        profileKey: "rohit_pal",
        stream: "B.PHARM",
        pdfPath: "/notes-pdf/medicinal-chemistry.pdf",
        uploadedAt: "2026-04-07",
    },
];

export const subject = [...new Set(notes.map((i) => i.title))];
export const author = [...new Set(notes.map((i) => i.author))];
